# Generated by Django 5.1 on 2024-12-09 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatermarkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_opacity', models.FloatField(default=0.5)),
                ('default_position_x', models.IntegerField(default=0)),
                ('default_position_y', models.IntegerField(default=0)),
                ('default_rotation', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatermarkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('TEXT', 'Text Watermark'), ('IMAGE', 'Image Watermark')], max_length=5)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='watermark_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatermarkedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='original_files/')),
                ('watermarked_file', models.FileField(upload_to='watermarked_files/')),
                ('file_type', models.CharField(choices=[('PDF', 'PDF Document'), ('IMAGE', 'Image File')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('opacity', models.FloatField(default=0.5)),
                ('rotation', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watermark_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.watermarktemplate')),
            ],
        ),
    ]
